cc_library(
    name = "SharpLCD",
    srcs = [
        "SharpLCD.cc",
    ],
    hdrs = [
        "SharpLCD.h",
    ],
    deps = [
        "@rules_pico//pico:hardware_gpio",
        "@rules_pico//pico:hardware_spi",
    ],
    visibility = ["//visibility:public"],
)