cc_library(
    name = "main",
    srcs = ["main.c"],
    hdrs = ["main.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//simulator:lvgl",
        "//simulator/ui/screens",
    ],
)
