cc_library(
    name = "adafruit_seesaw",
    srcs = ["adafruit_seesaw.cc"],
    hdrs = ["adafruit_seesaw.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//tplp/bus:i2c",
    ],
)
