cc_library(
    name = "adafruit_seesaw",
    srcs = [
        "adafruit_seesaw.cc",
        "defs.h",
    ],
    hdrs = ["adafruit_seesaw.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//picolog",
        "//picolog:status",
        "//tplp/bus:i2c",
    ],
)
