cc_library(
    name = "stepper",
    srcs = ["stepper.cc"],
    hdrs = ["stepper.h"],
    deps = [
        "//picolog",
        "//tplp/bus:types",
        "@rules_pico//pico:hardware_dma",
        "@rules_pico//pico:hardware_pwm",
    ],
)
